# permissions for end users to edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-editor-role
rules:
  - apiGroups:
      - samplecontroller.ginoh.github.io
    resources:
      - foos
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samplecontroller.ginoh.github.io
    resources:
      - foos/status
    verbs:
      - get
