apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-canary-analysis
spec:
  replicas: 4
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      steps:
        - setWeight: 25
        - pause: { duration: 1 }
        - analysis:
            templates:
              - templateName: curl-check
            args:
              - name: service-name
                value: rollouts-demo-canary
              - name: namespace
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: service-port
                value: "80"
              - name: service-path
                value: /color
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: localhost/argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
