registries:
  #- name: gcr.io/myproject-staging-area # publicly readable, does not need a service account for access
  - name: us-central1-docker.pkg.dev/${projectId}/quickstart-docker-repo
    src: true # mark it as the source registry (required)
    service-account: ${serviceAccount}
  #- name: gcr.io/myproject-production
  - name: us-central1-docker.pkg.dev/${projectId}/quickstart-docker-repo-prod
    service-account: ${serviceAccount}
