apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
    - name: gitUrl
      type: string
    - name: gitRevision
      type: string
    - name: containerRegistryName
      type: string
    - name: containerRepositoryName
      type: string
    - name: deployManifest
      type: string
  workspaces:
    - name: shared
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared
          subPath: source
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
    - name: build-and-push
      taskRef:
        name: buildkit-daemonless
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared
          subPath: source
        - name: credentials
          workspace: shared
          subPath: credentials
      params:
        - name: containerRegistryName
          value: $(params.containerRegistryName)
        - name: containerRepositoryName
          value: $(params.containerRepositoryName)
    - name: replace-registry-name
      taskRef:
        name: bash-replace-string
      runAfter:
        - build-and-push
      params:
        - name: source
          value: $(tasks.build-and-push.results.imageNameWithTag)
        - name: target
          value: $(params.containerRegistryName)
        - name: replace
          value: localhost:5000
    - name: configure-manifest
      taskRef:
        name: replace-image
      runAfter:
        - replace-registry-name
      workspaces:
        - name: source
          workspace: shared
          subPath: source
        - name: output
          workspace: shared
          subPath: manifests
      params:
        - name: pathToManifest
          value: $(params.deployManifest)
        - name: targetYamlPath
          value: .spec.template.spec.containers[0].image
        - name: imageName
          value: $(tasks.replace-registry-name.results.output)
    - name: deploy
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - configure-manifest
      workspaces:
        - name: manifests
          workspace: shared
          subPath: manifests
