apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildkit-daemonless
  annotations:
    container.apparmor.security.beta.kubernetes.io/step-build-and-push: unconfined
spec:
  results:
    - name: imageNameWithTag
      description: The name with tag of the image to build (e.g. image:latest)
    - name: imageNameWithDigest
      description: The name with digest of the image to build (e.g. image:@sha256xxx...)
  workspaces:
    - name: source
    - name: credentials
  params:
    - name: pathToDockerfile
      description: The path to the Dockerfile
      default: Dockerfile
    - name: containerRegistryName
      description: The Host Name of the Container Registry (e.g. myregistry:5000)
      default: "registry-1.docker.io"
    - name: containerRepositoryName
      description: The name of the repository (e.g. samples/hello-world)
    - name: imageTag
      description: The tag of the image to build
      default: latest
    - name: BUILDKIT_IMAGE
      description: The name of the BuildKit image
      default: moby/buildkit:master-rootless
    - name: credentialDirectory
      description: The directory name placed credential to push image
      default: $(workspaces.credentials.path)
  steps:
    - name: build-and-push
      image: $(params.BUILDKIT_IMAGE)
      workingDir: $(workspaces.source.path)
      command:
        - buildctl-daemonless.sh
      args: [
          "--debug",
          "build",
          "--progress",
          "plain",
          "--frontend",
          "dockerfile.v0",
          "--opt",
          "filename=$(params.pathToDockerfile)",
          "--local",
          "context=.",
          "--local",
          "dockerfile=.",
          "--output",
          # insecure Registry setting
          "type=image,name=$(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag),push=true,registry.insecure=true",
          # "type=image,name=$(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag),push=true",
          "--export-cache",
          "type=registry,ref=$(params.containerRegistryName)/$(params.containerRepositoryName):buildcache",
          "--import-cache",
          "type=registry,ref=$(params.containerRegistryName)/$(params.containerRepositoryName):buildcache",
          "--metadata-file",
          "metadata.json",
        ]
      env:
        - name: BUILDKITD_FLAGS
          # config flag is used to use insecure Registry
          value: --oci-worker-no-process-sandbox --config=/home/user/.config/buildkit/buildkitd.toml
        - name: DOCKER_CONFIG
          value: $(params.credentialDirectory)
      securityContext:
        seccompProfile:
          type: Unconfined
      volumeMounts:
        - name: buildkit-config
          mountPath: /home/user/.config/buildkit
    - name: resolve-image-name
      image: stedolan/jq
      script: |
        digest=`jq -r '.["containerimage.digest"]' $(workspaces.source.path)/metadata.json`
        echo "imageNameWithTag:"
        echo -n $(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag) | tee $(results.imageNameWithTag.path)
        echo ""
        echo "imageNameWithDigest:"
        echo -n $(params.containerRegistryName)/$(params.containerRepositoryName)@${digest} | tee $(results.imageNameWithDigest.path)
  volumes:
    - name: buildkit-config
      configMap:
        name: buildkit
---
# for insecure Registry
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit
data:
  buildkitd.toml: |
    [registry."registry.kube-system.svc.cluster.local"]
      http = true
      insecure = true
