apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildkit-daemonless
  annotations:
    container.apparmor.security.beta.kubernetes.io/step-build-and-push: unconfined
spec:
  results:
    - name: imageNameWithTag
      description: The name with tag of the image to build (e.g. image:latest)
    - name: imageNameWithDigest
      description: The name with digest of the image to build (e.g. image:@sha256xxx...)
  workspaces:
    - name: source
    - name: credentials
  params:
    - name: pathToDockerfile
      description: The path to the Dockerfile
      default: Dockerfile
    - name: containerRegistryName
      description: The Host Name of the Container Registry (e.g. myregistry:5000)
      default: "registry-1.docker.io"
    - name: containerRepositoryName
      description: The name of the repository (e.g. samples/hello-world)
    - name: imageTag
      description: The tag of the image to build
      default: latest
    - name: BUILDKIT_IMAGE
      description: The name of the BuildKit image
      default: moby/buildkit:master-rootless
    - name: credentialDirectory
      description: The directory name placed credential to push image
      default: $(workspaces.credentials.path)
  steps:
    - name: build-and-push
      image: $(params.BUILDKIT_IMAGE)
      workingDir: $(workspaces.source.path)
      command:
        - buildctl-daemonless.sh
      args: [
          "--debug",
          "build",
          "--progress",
          "plain",
          "--frontend",
          "dockerfile.v0",
          "--opt",
          "filename=$(params.pathToDockerfile)",
          "--local",
          "context=.",
          "--local",
          "dockerfile=.",
          "--output",
          "type=image,name=$(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag),push=true",
          "--export-cache",
          "type=registry,ref=$(params.containerRegistryName)/$(params.containerRepositoryName):buildcache",
          "--import-cache",
          "type=registry,ref=$(params.containerRegistryName)/$(params.containerRepositoryName):buildcache",
          # insecure Registry setting
          #"type=image,name=$(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag),push=true,registry.insecure=true",
          #"--export-cache",
          #"type=inline",
          #"--import-cache",
          #"type=registry,ref=$(params.containerRegistryName)/$(params.containerRepositoryName)",
          "--metadata-file",
          "metadata.json",
        ]
      env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
        - name: DOCKER_CONFIG
          value: $(params.credentialDirectory)
      securityContext:
        seccompProfile:
          type: Unconfined
    - name: resolve-image-name
      image: stedolan/jq
      script: |
        digest=`jq -r '.["containerimage.digest"]' $(workspaces.source.path)/metadata.json`
        echo "imageNameWithTag:"
        echo -n $(params.containerRegistryName)/$(params.containerRepositoryName):$(params.imageTag) | tee $(results.imageNameWithTag.path)
        echo ""
        echo "imageNameWithDigest:"
        echo -n $(params.containerRegistryName)/$(params.containerRepositoryName)@$digest | tee $(results.imageNameWithDigest.path)
