apiVersion: v1
kind: Pod
metadata:
  name: sample-initcontainer
spec:
  initContainers:
    - name: init-1
      image: centos:8
      command:
        - sh
        - -c
        - echo sample-init-1 > /usr/share/nginx/html/sample-init-1.html
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/
    - name: init-2
      image: centos:8
      command:
      command:
        - sh
        - -c
        - echo sample-init-2 > /usr/share/nginx/html/sample-init-2.html
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/
  restartPolicy: Always
  volumes:
    - name: html-volume
      emptyDir: {}
