apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab-test
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          env:
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-initial-root-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-outside
  namespace: gitlab-test
  labels:
    app: gitlab-outside
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
      protocol: TCP
  selector:
    app: gitlab
---
# https://www.orzs.tech/use-gitlab-in-kubernetes/
