# permissions for end users to view foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foo-viewer-role
rules:
  - apiGroups:
      - samplecontroller.ginoh.github.io
    resources:
      - foos
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samplecontroller.ginoh.github.io
    resources:
      - foos/status
    verbs:
      - get
