apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: post-analysis-test
spec:
  args:
    - name: service-name
  metrics:
    - name: webmetric
      initialDelay: 30s
      failureLimit: 2
      interval: 10s
      count: 3
      successCondition: result == "yellow" || result == "blue"
      provider:
        web:
          url: "http://{{ args.service-name }}/color"
