apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-sample
  namespace: test-self-signed
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-sample
spec:
  subject:
    organizations:
      - MyOrg
    countries:
      - Japan
    localities:
      - Chiyoda-ku
    provinces:
      - Tokyo
  dnsNames:
    - "*.example.com"
  secretName: self-signed-example-com
  issuerRef:
    name: self-signed-sample
    kind: Issuer
