apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-apply
  namespace: getting-started
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-apply
  namespace: getting-started
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: kubectl-apply
    namespace: getting-started
