---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-samplecontroller-ginoh-github-io-v1alpha1-foo
  failurePolicy: Fail
  name: mfoo.kb.io
  rules:
  - apiGroups:
    - samplecontroller.ginoh.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - foos
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-samplecontroller-ginoh-github-io-v1alpha1-foo
  failurePolicy: Fail
  name: vfoo.kb.io
  rules:
  - apiGroups:
    - samplecontroller.ginoh.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - foos
  sideEffects: None
