apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: "0"
webhook:
  port: 9443
leaderElection:
  leaderElect: false
  resourceName: 3893da7a.ginoh.github.io
