apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: reserved-instance
spec:
  image: ghcr.io/kubewarden/policy-server:v0.2.6
  replicas: 2
  serviceAccountName: policy-server
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
