apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-run-
spec:
  params:
    - name: gitRevision
      value: main
    - name: gitUrl
      value: https://github.com/ginoh/sample-hello-world.git
    - name: containerRegistryName
      value: registry.kube-system.svc.cluster.local
    - name: containerRepositoryName
      value: samples/hello-world
    - name: deployManifest
      value: kubernetes/deployment.yaml
  pipelineRef:
    name: build-and-deploy
  podTemplate:
    securityContext:
      fsGroup: 65532
  taskRunSpecs:
    - pipelineTaskName: deploy
      taskServiceAccountName: kubectl-apply
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          storageClassName: csi-hostpath-sc
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
