apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-server
      version: v1
  template:
    metadata:
      labels:
        app: sample-server
        version: v1
    spec:
      containers:
        - name: sample-server
          image: localhost/ginoh/sample-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-server
